apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: learnk8s/knote-java:1.0.0
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            #              valueFrom :
            #                configMapKeyRef :
            #                  name : db-config
            #                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              value: morris
            #              valueFrom :
            #                configMapKeyRef :
            #                  name : db-config
            #                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            #              valueFrom :
            #                secretKeyRef :
            #                  name : mysql-secrets
            #                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              value: mysql
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
